const CONFIG = {
  DB_SCHEMA_VERSION: 2,
  CLIENT_VERSION: "2026.03.12.3",
  DAILY_PRODUCTIVITY_THRESHOLD_MINUTES: 240,
  DISTRACTION_BUDGET_MINUTES: 90,
  STORAGE_KEYS: {
    TASKS: "discipline_tracker_tasks",
    FAVORITES: "discipline_tracker_favorites",
    STREAK: "discipline_tracker_streak",
    LAST_ACTIVITY: "discipline_tracker_last_activity",
    ACTIVE_TASK: "discipline_tracker_active_task",
    SCHEMA_VERSION: "discipline_tracker_schema_version",
    SYNC_ENDPOINT: "discipline_tracker_sync_endpoint",
    SYNC_DEVICE_ID: "discipline_tracker_device_id",
    SYNC_QUEUE: "discipline_tracker_sync_queue",
    SHADOW_AVG: "discipline_tracker_shadow_avg",
    TRAINER_STATE: "discipline_tracker_trainer_state",
    FLOW_PROTOCOL: "discipline_tracker_flow_protocol",
    ROADMAP_STATE: "discipline_tracker_roadmap_state",
    FIREBASE_USER: "discipline_tracker_firebase_user",
    CLIENT_VERSION: "discipline_tracker_client_version",
    TIMER_CLOUD_STATE: "discipline_tracker_timer_cloud_state",
  },
  MOTIVATION_INTERVAL: 15000,
  CHART_RANGES: { "7d": 7, "30d": 30, "3m": 90, "6m": 180, "1y": 365 },
  FIREBASE_PROTECTION: {
    MAX_WRITES_PER_MINUTE: 60,
    WRITE_DEBOUNCE_MS: 1200,
    MAX_TASKS_SYNC: 2000,
    MAX_FAVORITES_SYNC: 200,
    MAX_TEXT_LEN: 180,
    MIN_MISSION_UPDATE_INTERVAL_MS: 2500,
  },
  DAILY_GOALS: [
    {
      id: "project",
      label: "Project Work",
      minutesTarget: 180,
      sessionsTarget: 0,
      keywords: ["project"],
    },
    {
      id: "revision",
      label: "Revision",
      minutesTarget: 120,
      sessionsTarget: 0,
      keywords: ["revision"],
    },
  ],
};
